index:
   path: /
   controller: App\Controller\DefaultController::index

analyze:
   path: /analyze
   controller: App\Controller\AnalyzeController::index

extract:
   path: /extract
   controller: App\Controller\ExtractController::index
   